# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Documents/GitHub/ECE4810J_FA2021/Lab3/pynq_hls_adder/pynq_hls_adder.srcs/sources_1/bd/pynq_hls_adder/ip/pynq_hls_adder_processing_system7_0_0/pynq_hls_adder_processing_system7_0_0.xci
# IP: The module: 'pynq_hls_adder_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/GitHub/ECE4810J_FA2021/Lab3/pynq_hls_adder/pynq_hls_adder.gen/sources_1/bd/pynq_hls_adder/ip/pynq_hls_adder_processing_system7_0_0/pynq_hls_adder_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pynq_hls_adder_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Documents/GitHub/ECE4810J_FA2021/Lab3/pynq_hls_adder/pynq_hls_adder.srcs/sources_1/bd/pynq_hls_adder/ip/pynq_hls_adder_processing_system7_0_0/pynq_hls_adder_processing_system7_0_0.xci
# IP: The module: 'pynq_hls_adder_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/GitHub/ECE4810J_FA2021/Lab3/pynq_hls_adder/pynq_hls_adder.gen/sources_1/bd/pynq_hls_adder/ip/pynq_hls_adder_processing_system7_0_0/pynq_hls_adder_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pynq_hls_adder_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
