# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/fir_filter/fir_filter.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_filter || ORIG_REF_NAME==fir_filter} -quiet] -quiet

# IP: bd/fir_filter/ip/fir_filter_processing_system7_0_0/fir_filter_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_filter_processing_system7_0_0 || ORIG_REF_NAME==fir_filter_processing_system7_0_0} -quiet] -quiet

# IP: bd/fir_filter/ip/fir_filter_fir_filter_0_0/fir_filter_fir_filter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_filter_fir_filter_0_0 || ORIG_REF_NAME==fir_filter_fir_filter_0_0} -quiet] -quiet

# IP: bd/fir_filter/ip/fir_filter_auto_pc_0/fir_filter_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_filter_auto_pc_0 || ORIG_REF_NAME==fir_filter_auto_pc_0} -quiet] -quiet

# IP: bd/fir_filter/ip/fir_filter_ps7_0_axi_periph_0/fir_filter_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_filter_ps7_0_axi_periph_0 || ORIG_REF_NAME==fir_filter_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/fir_filter/ip/fir_filter_rst_ps7_0_100M_0/fir_filter_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_filter_rst_ps7_0_100M_0 || ORIG_REF_NAME==fir_filter_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: d:/Documents/GitHub/ECE4810J_FA2021/Project/FIR_Filter/FIR_Filter.gen/sources_1/bd/fir_filter/fir_filter_ooc.xdc
