# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Documents/GitHub/ECE4810J_FA2021/ZynqComputer/ZynqComputer.srcs/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_xbar_0/Zynq_CPU_xbar_0.xci
# IP: The module: 'Zynq_CPU_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/GitHub/ECE4810J_FA2021/ZynqComputer/ZynqComputer.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_xbar_0/Zynq_CPU_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_CPU_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Documents/GitHub/ECE4810J_FA2021/ZynqComputer/ZynqComputer.srcs/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_xbar_0/Zynq_CPU_xbar_0.xci
# IP: The module: 'Zynq_CPU_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/GitHub/ECE4810J_FA2021/ZynqComputer/ZynqComputer.gen/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_xbar_0/Zynq_CPU_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_CPU_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
