# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/pynq_hls_adder/pynq_hls_adder.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_hls_adder || ORIG_REF_NAME==pynq_hls_adder} -quiet] -quiet

# IP: bd/pynq_hls_adder/ip/pynq_hls_adder_processing_system7_0_0/pynq_hls_adder_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_hls_adder_processing_system7_0_0 || ORIG_REF_NAME==pynq_hls_adder_processing_system7_0_0} -quiet] -quiet

# IP: bd/pynq_hls_adder/ip/pynq_hls_adder_hls_adder_0_1/pynq_hls_adder_hls_adder_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_hls_adder_hls_adder_0_1 || ORIG_REF_NAME==pynq_hls_adder_hls_adder_0_1} -quiet] -quiet

# IP: bd/pynq_hls_adder/ip/pynq_hls_adder_ps7_0_axi_periph_0/pynq_hls_adder_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_hls_adder_ps7_0_axi_periph_0 || ORIG_REF_NAME==pynq_hls_adder_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/pynq_hls_adder/ip/pynq_hls_adder_rst_ps7_0_100M_0/pynq_hls_adder_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_hls_adder_rst_ps7_0_100M_0 || ORIG_REF_NAME==pynq_hls_adder_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/pynq_hls_adder/ip/pynq_hls_adder_auto_pc_0/pynq_hls_adder_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_hls_adder_auto_pc_0 || ORIG_REF_NAME==pynq_hls_adder_auto_pc_0} -quiet] -quiet

# XDC: d:/Documents/GitHub/ECE4810J_FA2021/Lab3/pynq_hls_adder/pynq_hls_adder.gen/sources_1/bd/pynq_hls_adder/pynq_hls_adder_ooc.xdc
