-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1.1 (64-bit)
-- Version: 2021.1.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity yuv_filter_entry_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    Y_scale : IN STD_LOGIC_VECTOR (7 downto 0);
    Y_scale_c_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    Y_scale_c_full_n : IN STD_LOGIC;
    Y_scale_c_write : OUT STD_LOGIC;
    U_scale : IN STD_LOGIC_VECTOR (7 downto 0);
    U_scale_c_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    U_scale_c_full_n : IN STD_LOGIC;
    U_scale_c_write : OUT STD_LOGIC;
    V_scale : IN STD_LOGIC_VECTOR (7 downto 0);
    V_scale_c_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    V_scale_c_full_n : IN STD_LOGIC;
    V_scale_c_write : OUT STD_LOGIC );
end;


architecture behav of yuv_filter_entry_proc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal Y_scale_c_blk_n : STD_LOGIC;
    signal U_scale_c_blk_n : STD_LOGIC;
    signal V_scale_c_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_start = ap_const_logic_0) or (ap_const_logic_0 = V_scale_c_full_n) or (ap_const_logic_0 = U_scale_c_full_n) or (ap_const_logic_0 = Y_scale_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, Y_scale_c_full_n, U_scale_c_full_n, V_scale_c_full_n)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    U_scale_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, U_scale_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            U_scale_c_blk_n <= U_scale_c_full_n;
        else 
            U_scale_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    U_scale_c_din <= U_scale;

    U_scale_c_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Y_scale_c_full_n, U_scale_c_full_n, V_scale_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_const_logic_0 = V_scale_c_full_n) or (ap_const_logic_0 = U_scale_c_full_n) or (ap_const_logic_0 = Y_scale_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            U_scale_c_write <= ap_const_logic_1;
        else 
            U_scale_c_write <= ap_const_logic_0;
        end if; 
    end process;


    V_scale_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, V_scale_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            V_scale_c_blk_n <= V_scale_c_full_n;
        else 
            V_scale_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    V_scale_c_din <= V_scale;

    V_scale_c_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Y_scale_c_full_n, U_scale_c_full_n, V_scale_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_const_logic_0 = V_scale_c_full_n) or (ap_const_logic_0 = U_scale_c_full_n) or (ap_const_logic_0 = Y_scale_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            V_scale_c_write <= ap_const_logic_1;
        else 
            V_scale_c_write <= ap_const_logic_0;
        end if; 
    end process;


    Y_scale_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Y_scale_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Y_scale_c_blk_n <= Y_scale_c_full_n;
        else 
            Y_scale_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    Y_scale_c_din <= Y_scale;

    Y_scale_c_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Y_scale_c_full_n, U_scale_c_full_n, V_scale_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_const_logic_0 = V_scale_c_full_n) or (ap_const_logic_0 = U_scale_c_full_n) or (ap_const_logic_0 = Y_scale_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Y_scale_c_write <= ap_const_logic_1;
        else 
            Y_scale_c_write <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg, Y_scale_c_full_n, U_scale_c_full_n, V_scale_c_full_n)
    begin
        if (((ap_start = ap_const_logic_0) or (ap_const_logic_0 = V_scale_c_full_n) or (ap_const_logic_0 = U_scale_c_full_n) or (ap_const_logic_0 = Y_scale_c_full_n) or (ap_done_reg = ap_const_logic_1))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, Y_scale_c_full_n, U_scale_c_full_n, V_scale_c_full_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_const_logic_0 = V_scale_c_full_n) or (ap_const_logic_0 = U_scale_c_full_n) or (ap_const_logic_0 = Y_scale_c_full_n) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Y_scale_c_full_n, U_scale_c_full_n, V_scale_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_const_logic_0 = V_scale_c_full_n) or (ap_const_logic_0 = U_scale_c_full_n) or (ap_const_logic_0 = Y_scale_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Y_scale_c_full_n, U_scale_c_full_n, V_scale_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_const_logic_0 = V_scale_c_full_n) or (ap_const_logic_0 = U_scale_c_full_n) or (ap_const_logic_0 = Y_scale_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

end behav;
