# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Documents/GitHub/ECE4810J_FA2021/Project/FIR_Filter/FIR_Filter.srcs/sources_1/bd/fir_filter/ip/fir_filter_rst_ps7_0_100M_0/fir_filter_rst_ps7_0_100M_0.xci
# IP: The module: 'fir_filter_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/GitHub/ECE4810J_FA2021/Project/FIR_Filter/FIR_Filter.gen/sources_1/bd/fir_filter/ip/fir_filter_rst_ps7_0_100M_0/fir_filter_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_filter_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Documents/GitHub/ECE4810J_FA2021/Project/FIR_Filter/FIR_Filter.gen/sources_1/bd/fir_filter/ip/fir_filter_rst_ps7_0_100M_0/fir_filter_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_filter_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Documents/GitHub/ECE4810J_FA2021/Project/FIR_Filter/FIR_Filter.gen/sources_1/bd/fir_filter/ip/fir_filter_rst_ps7_0_100M_0/fir_filter_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_filter_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Documents/GitHub/ECE4810J_FA2021/Project/FIR_Filter/FIR_Filter.srcs/sources_1/bd/fir_filter/ip/fir_filter_rst_ps7_0_100M_0/fir_filter_rst_ps7_0_100M_0.xci
# IP: The module: 'fir_filter_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/GitHub/ECE4810J_FA2021/Project/FIR_Filter/FIR_Filter.gen/sources_1/bd/fir_filter/ip/fir_filter_rst_ps7_0_100M_0/fir_filter_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_filter_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Documents/GitHub/ECE4810J_FA2021/Project/FIR_Filter/FIR_Filter.gen/sources_1/bd/fir_filter/ip/fir_filter_rst_ps7_0_100M_0/fir_filter_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_filter_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Documents/GitHub/ECE4810J_FA2021/Project/FIR_Filter/FIR_Filter.gen/sources_1/bd/fir_filter/ip/fir_filter_rst_ps7_0_100M_0/fir_filter_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_filter_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
