-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1.1 (64-bit)
-- Version: 2021.1.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity yuv_filter_rgb2yuv_1_Pipeline_RGB2YUV_LOOP_X_RGB2YUV_LOOP_Y is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    out_channels_ch1_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    out_channels_ch1_full_n : IN STD_LOGIC;
    out_channels_ch1_write : OUT STD_LOGIC;
    out_channels_ch2_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    out_channels_ch2_full_n : IN STD_LOGIC;
    out_channels_ch2_write : OUT STD_LOGIC;
    out_channels_ch3_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    out_channels_ch3_full_n : IN STD_LOGIC;
    out_channels_ch3_write : OUT STD_LOGIC;
    bound : IN STD_LOGIC_VECTOR (31 downto 0);
    height : IN STD_LOGIC_VECTOR (15 downto 0);
    in_channels_ch1_address0 : OUT STD_LOGIC_VECTOR (21 downto 0);
    in_channels_ch1_ce0 : OUT STD_LOGIC;
    in_channels_ch1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    in_channels_ch2_address0 : OUT STD_LOGIC_VECTOR (21 downto 0);
    in_channels_ch2_ce0 : OUT STD_LOGIC;
    in_channels_ch2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    in_channels_ch3_address0 : OUT STD_LOGIC_VECTOR (21 downto 0);
    in_channels_ch3_ce0 : OUT STD_LOGIC;
    in_channels_ch3_q0 : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of yuv_filter_rgb2yuv_1_Pipeline_RGB2YUV_LOOP_X_RGB2YUV_LOOP_Y is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv10_80 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv8_10 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv15_7FDA : STD_LOGIC_VECTOR (14 downto 0) := "111111111011010";
    constant ap_const_lv15_80 : STD_LOGIC_VECTOR (14 downto 0) := "000000010000000";
    constant ap_const_lv15_7A : STD_LOGIC_VECTOR (14 downto 0) := "000000001111010";
    constant ap_const_lv13_19 : STD_LOGIC_VECTOR (12 downto 0) := "0000000011001";
    constant ap_const_lv16_FFB6 : STD_LOGIC_VECTOR (15 downto 0) := "1111111110110110";
    constant ap_const_lv16_FFA2 : STD_LOGIC_VECTOR (15 downto 0) := "1111111110100010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln49_fu_216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal out_channels_ch1_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal out_channels_ch2_blk_n : STD_LOGIC;
    signal out_channels_ch3_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln52_fu_230_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_reg_611 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln34_fu_235_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln34_reg_616 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln54_1_fu_308_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal add_ln54_1_reg_621 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln54_1_fu_319_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln54_1_reg_626 : STD_LOGIC_VECTOR (63 downto 0);
    signal R_reg_647 : STD_LOGIC_VECTOR (7 downto 0);
    signal R_reg_647_pp0_iter5_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal R_reg_647_pp0_iter6_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln57_fu_323_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal G_reg_659 : STD_LOGIC_VECTOR (7 downto 0);
    signal G_reg_659_pp0_iter6_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal G_reg_659_pp0_iter7_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal B_reg_665 : STD_LOGIC_VECTOR (7 downto 0);
    signal B_reg_665_pp0_iter6_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal B_reg_665_pp0_iter7_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln57_3_fu_327_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln57_fu_370_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln57_reg_688 : STD_LOGIC_VECTOR (14 downto 0);
    signal shl_ln58_1_fu_376_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln58_1_reg_693 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln_reg_708 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln5_reg_713 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln6_reg_718 : STD_LOGIC_VECTOR (7 downto 0);
    signal y_2_fu_114 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_fu_243_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal x_fu_118 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln34_1_fu_268_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal indvar_flatten_fu_122 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln49_fu_221_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal x_4_fu_262_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln54_fu_275_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln54_1_fu_287_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_cast_fu_279_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_2_cast_fu_291_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal add_ln54_fu_299_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln54_fu_305_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal shl_ln_fu_335_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln57_1_fu_346_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln57_2_fu_353_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln57_1_fu_360_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln57_7_fu_366_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln57_1_fu_342_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_531_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln58_1_fu_383_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub_ln59_fu_390_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln2_fu_400_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln59_fu_396_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln59_fu_407_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sub_ln59_1_fu_411_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_540_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln59_1_fu_421_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln59_1_fu_417_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln57_2_fu_430_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln57_5_fu_437_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln57_8_fu_441_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_549_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln57_9_fu_450_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln57_3_fu_444_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln57_2_fu_453_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1_fu_469_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln58_fu_476_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln58_2_fu_480_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_558_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln58_fu_483_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_2_fu_489_p2 : STD_LOGIC_VECTOR (15 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of add_ln58_2_fu_489_p2 : signal is "no";
    signal grp_fu_567_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_531_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_531_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_531_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_540_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_540_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_540_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_549_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_549_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_549_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_558_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_558_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_567_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_567_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_567_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_531_ce : STD_LOGIC;
    signal grp_fu_540_ce : STD_LOGIC;
    signal grp_fu_549_ce : STD_LOGIC;
    signal grp_fu_558_ce : STD_LOGIC;
    signal grp_fu_567_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal grp_fu_549_p00 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_549_p20 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component yuv_filter_mac_muladd_8ns_7s_8ns_15_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component yuv_filter_mac_muladd_8ns_7ns_8ns_15_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component yuv_filter_mac_muladd_8ns_5ns_8ns_13_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (12 downto 0) );
    end component;


    component yuv_filter_mac_muladd_8ns_8s_15s_16_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component yuv_filter_mac_muladd_8ns_8s_16s_16_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component yuv_filter_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mac_muladd_8ns_7s_8ns_15_4_1_U7 : component yuv_filter_mac_muladd_8ns_7s_8ns_15_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 7,
        din2_WIDTH => 8,
        dout_WIDTH => 15)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_531_p0,
        din1 => grp_fu_531_p1,
        din2 => grp_fu_531_p2,
        ce => grp_fu_531_ce,
        dout => grp_fu_531_p3);

    mac_muladd_8ns_7ns_8ns_15_4_1_U8 : component yuv_filter_mac_muladd_8ns_7ns_8ns_15_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 7,
        din2_WIDTH => 8,
        dout_WIDTH => 15)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_540_p0,
        din1 => grp_fu_540_p1,
        din2 => grp_fu_540_p2,
        ce => grp_fu_540_ce,
        dout => grp_fu_540_p3);

    mac_muladd_8ns_5ns_8ns_13_4_1_U9 : component yuv_filter_mac_muladd_8ns_5ns_8ns_13_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 5,
        din2_WIDTH => 8,
        dout_WIDTH => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_549_p0,
        din1 => grp_fu_549_p1,
        din2 => grp_fu_549_p2,
        ce => grp_fu_549_ce,
        dout => grp_fu_549_p3);

    mac_muladd_8ns_8s_15s_16_4_1_U10 : component yuv_filter_mac_muladd_8ns_8s_15s_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 15,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_558_p0,
        din1 => grp_fu_558_p1,
        din2 => grp_fu_531_p3,
        ce => grp_fu_558_ce,
        dout => grp_fu_558_p3);

    mac_muladd_8ns_8s_16s_16_4_1_U11 : component yuv_filter_mac_muladd_8ns_8s_16s_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_567_p0,
        din1 => grp_fu_567_p1,
        din2 => grp_fu_567_p2,
        ce => grp_fu_567_ce,
        dout => grp_fu_567_p3);

    flow_control_loop_pipe_sequential_init_U : component yuv_filter_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_122 <= ap_const_lv32_0;
                elsif (((icmp_ln49_fu_216_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten_fu_122 <= add_ln49_fu_221_p2;
                end if;
            end if; 
        end if;
    end process;

    x_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    x_fu_118 <= ap_const_lv16_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    x_fu_118 <= select_ln34_1_fu_268_p3;
                end if;
            end if; 
        end if;
    end process;

    y_2_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    y_2_fu_114 <= ap_const_lv16_0;
                elsif (((icmp_ln49_fu_216_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    y_2_fu_114 <= y_fu_243_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                B_reg_665 <= in_channels_ch3_q0;
                B_reg_665_pp0_iter6_reg <= B_reg_665;
                B_reg_665_pp0_iter7_reg <= B_reg_665_pp0_iter6_reg;
                G_reg_659 <= in_channels_ch2_q0;
                G_reg_659_pp0_iter6_reg <= G_reg_659;
                G_reg_659_pp0_iter7_reg <= G_reg_659_pp0_iter6_reg;
                R_reg_647 <= in_channels_ch1_q0;
                R_reg_647_pp0_iter5_reg <= R_reg_647;
                R_reg_647_pp0_iter6_reg <= R_reg_647_pp0_iter5_reg;
                add_ln54_1_reg_621 <= add_ln54_1_fu_308_p2;
                    add_ln57_reg_688(14 downto 1) <= add_ln57_fu_370_p2(14 downto 1);
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                    shl_ln58_1_reg_693(11 downto 4) <= shl_ln58_1_fu_376_p3(11 downto 4);
                trunc_ln5_reg_713 <= add_ln58_2_fu_489_p2(15 downto 8);
                trunc_ln6_reg_718 <= grp_fu_567_p3(15 downto 8);
                trunc_ln_reg_708 <= add_ln57_2_fu_453_p2(15 downto 8);
                    zext_ln54_1_reg_626(21 downto 0) <= zext_ln54_1_fu_319_p1(21 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln49_fu_216_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln52_reg_611 <= icmp_ln52_fu_230_p2;
                select_ln34_reg_616 <= select_ln34_fu_235_p3;
            end if;
        end if;
    end process;
    zext_ln54_1_reg_626(63 downto 22) <= "000000000000000000000000000000000000000000";
    add_ln57_reg_688(0) <= '0';
    shl_ln58_1_reg_693(3 downto 0) <= "0000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln49_fu_221_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_122) + unsigned(ap_const_lv32_1));
    add_ln54_1_fu_308_p2 <= std_logic_vector(unsigned(add_ln54_fu_299_p2) + unsigned(zext_ln54_fu_305_p1));
    add_ln54_fu_299_p2 <= std_logic_vector(unsigned(tmp_cast_fu_279_p3) + unsigned(tmp_2_cast_fu_291_p3));
    add_ln57_1_fu_360_p2 <= std_logic_vector(unsigned(zext_ln57_2_fu_353_p1) + unsigned(ap_const_lv10_80));
    add_ln57_2_fu_453_p2 <= std_logic_vector(unsigned(zext_ln57_9_fu_450_p1) + unsigned(add_ln57_3_fu_444_p2));
    add_ln57_3_fu_444_p2 <= std_logic_vector(unsigned(zext_ln57_5_fu_437_p1) + unsigned(zext_ln57_8_fu_441_p1));
    add_ln57_fu_370_p2 <= std_logic_vector(unsigned(zext_ln57_7_fu_366_p1) + unsigned(zext_ln57_1_fu_342_p1));
    add_ln58_2_fu_489_p2 <= std_logic_vector(signed(grp_fu_558_p3) + signed(sub_ln58_fu_483_p2));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter9, out_channels_ch1_full_n, out_channels_ch2_full_n, out_channels_ch3_full_n)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and ((out_channels_ch3_full_n = ap_const_logic_0) or (out_channels_ch2_full_n = ap_const_logic_0) or (out_channels_ch1_full_n = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter9, out_channels_ch1_full_n, out_channels_ch2_full_n, out_channels_ch3_full_n)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and ((out_channels_ch3_full_n = ap_const_logic_0) or (out_channels_ch2_full_n = ap_const_logic_0) or (out_channels_ch1_full_n = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter9, out_channels_ch1_full_n, out_channels_ch2_full_n, out_channels_ch3_full_n)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and ((out_channels_ch3_full_n = ap_const_logic_0) or (out_channels_ch2_full_n = ap_const_logic_0) or (out_channels_ch1_full_n = ap_const_logic_0)));
    end process;


    ap_block_state10_pp0_stage0_iter9_assign_proc : process(out_channels_ch1_full_n, out_channels_ch2_full_n, out_channels_ch3_full_n)
    begin
                ap_block_state10_pp0_stage0_iter9 <= ((out_channels_ch3_full_n = ap_const_logic_0) or (out_channels_ch2_full_n = ap_const_logic_0) or (out_channels_ch1_full_n = ap_const_logic_0));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln49_fu_216_p2)
    begin
        if (((icmp_ln49_fu_216_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter8_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_531_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_531_ce <= ap_const_logic_1;
        else 
            grp_fu_531_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_531_p0 <= zext_ln57_fu_323_p1(8 - 1 downto 0);
    grp_fu_531_p1 <= ap_const_lv15_7FDA(7 - 1 downto 0);
    grp_fu_531_p2 <= ap_const_lv15_80(8 - 1 downto 0);

    grp_fu_540_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_540_ce <= ap_const_logic_1;
        else 
            grp_fu_540_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_540_p0 <= zext_ln57_fu_323_p1(8 - 1 downto 0);
    grp_fu_540_p1 <= ap_const_lv15_7A(7 - 1 downto 0);
    grp_fu_540_p2 <= ap_const_lv15_80(8 - 1 downto 0);

    grp_fu_549_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_549_ce <= ap_const_logic_1;
        else 
            grp_fu_549_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_549_p0 <= grp_fu_549_p00(8 - 1 downto 0);
    grp_fu_549_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_channels_ch3_q0),13));
    grp_fu_549_p1 <= ap_const_lv13_19(5 - 1 downto 0);
    grp_fu_549_p2 <= grp_fu_549_p20(8 - 1 downto 0);
    grp_fu_549_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(G_reg_659_pp0_iter6_reg),13));

    grp_fu_558_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_558_ce <= ap_const_logic_1;
        else 
            grp_fu_558_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_558_p0 <= zext_ln57_3_fu_327_p1(8 - 1 downto 0);
    grp_fu_558_p1 <= ap_const_lv16_FFB6(8 - 1 downto 0);

    grp_fu_567_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_567_ce <= ap_const_logic_1;
        else 
            grp_fu_567_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_567_p0 <= zext_ln57_3_fu_327_p1(8 - 1 downto 0);
    grp_fu_567_p1 <= ap_const_lv16_FFA2(8 - 1 downto 0);
    grp_fu_567_p2 <= std_logic_vector(unsigned(zext_ln59_1_fu_421_p1) + unsigned(sext_ln59_1_fu_417_p1));
    icmp_ln49_fu_216_p2 <= "1" when (indvar_flatten_fu_122 = bound) else "0";
    icmp_ln52_fu_230_p2 <= "1" when (y_2_fu_114 = height) else "0";
    in_channels_ch1_address0 <= zext_ln54_1_fu_319_p1(22 - 1 downto 0);

    in_channels_ch1_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            in_channels_ch1_ce0 <= ap_const_logic_1;
        else 
            in_channels_ch1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    in_channels_ch2_address0 <= zext_ln54_1_reg_626(22 - 1 downto 0);

    in_channels_ch2_ce0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            in_channels_ch2_ce0 <= ap_const_logic_1;
        else 
            in_channels_ch2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    in_channels_ch3_address0 <= zext_ln54_1_reg_626(22 - 1 downto 0);

    in_channels_ch3_ce0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            in_channels_ch3_ce0 <= ap_const_logic_1;
        else 
            in_channels_ch3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    out_channels_ch1_blk_n_assign_proc : process(ap_enable_reg_pp0_iter9, out_channels_ch1_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then 
            out_channels_ch1_blk_n <= out_channels_ch1_full_n;
        else 
            out_channels_ch1_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_channels_ch1_din <= std_logic_vector(unsigned(trunc_ln_reg_708) + unsigned(ap_const_lv8_10));

    out_channels_ch1_write_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then 
            out_channels_ch1_write <= ap_const_logic_1;
        else 
            out_channels_ch1_write <= ap_const_logic_0;
        end if; 
    end process;


    out_channels_ch2_blk_n_assign_proc : process(ap_enable_reg_pp0_iter9, out_channels_ch2_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then 
            out_channels_ch2_blk_n <= out_channels_ch2_full_n;
        else 
            out_channels_ch2_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_channels_ch2_din <= (trunc_ln5_reg_713 xor ap_const_lv8_80);

    out_channels_ch2_write_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then 
            out_channels_ch2_write <= ap_const_logic_1;
        else 
            out_channels_ch2_write <= ap_const_logic_0;
        end if; 
    end process;


    out_channels_ch3_blk_n_assign_proc : process(ap_enable_reg_pp0_iter9, out_channels_ch3_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then 
            out_channels_ch3_blk_n <= out_channels_ch3_full_n;
        else 
            out_channels_ch3_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_channels_ch3_din <= (trunc_ln6_reg_718 xor ap_const_lv8_80);

    out_channels_ch3_write_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then 
            out_channels_ch3_write <= ap_const_logic_1;
        else 
            out_channels_ch3_write <= ap_const_logic_0;
        end if; 
    end process;

    select_ln34_1_fu_268_p3 <= 
        x_4_fu_262_p2 when (icmp_ln52_reg_611(0) = '1') else 
        x_fu_118;
    select_ln34_fu_235_p3 <= 
        ap_const_lv16_0 when (icmp_ln52_fu_230_p2(0) = '1') else 
        y_2_fu_114;
        sext_ln59_1_fu_417_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln59_1_fu_411_p2),16));

        sext_ln59_fu_396_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln59_fu_390_p2),14));

    shl_ln1_fu_469_p3 <= (B_reg_665_pp0_iter7_reg & ap_const_lv7_0);
    shl_ln2_fu_400_p3 <= (B_reg_665_pp0_iter6_reg & ap_const_lv1_0);
    shl_ln57_1_fu_346_p3 <= (R_reg_647_pp0_iter6_reg & ap_const_lv1_0);
    shl_ln57_2_fu_430_p3 <= (G_reg_659_pp0_iter7_reg & ap_const_lv7_0);
    shl_ln58_1_fu_376_p3 <= (B_reg_665_pp0_iter6_reg & ap_const_lv4_0);
    shl_ln_fu_335_p3 <= (R_reg_647_pp0_iter6_reg & ap_const_lv6_0);
    sub_ln58_fu_483_p2 <= std_logic_vector(unsigned(zext_ln58_fu_476_p1) - unsigned(zext_ln58_2_fu_480_p1));
    sub_ln59_1_fu_411_p2 <= std_logic_vector(signed(sext_ln59_fu_396_p1) - signed(zext_ln59_fu_407_p1));
    sub_ln59_fu_390_p2 <= std_logic_vector(unsigned(ap_const_lv13_0) - unsigned(zext_ln58_1_fu_383_p1));
    tmp_2_cast_fu_291_p3 <= (trunc_ln54_1_fu_287_p1 & ap_const_lv8_0);
    tmp_cast_fu_279_p3 <= (trunc_ln54_fu_275_p1 & ap_const_lv10_0);
    trunc_ln54_1_fu_287_p1 <= select_ln34_1_fu_268_p3(14 - 1 downto 0);
    trunc_ln54_fu_275_p1 <= select_ln34_1_fu_268_p3(12 - 1 downto 0);
    x_4_fu_262_p2 <= std_logic_vector(unsigned(x_fu_118) + unsigned(ap_const_lv16_1));
    y_fu_243_p2 <= std_logic_vector(unsigned(select_ln34_fu_235_p3) + unsigned(ap_const_lv16_1));
    zext_ln54_1_fu_319_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln54_1_reg_621),64));
    zext_ln54_fu_305_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln34_reg_616),22));
    zext_ln57_1_fu_342_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_335_p3),15));
    zext_ln57_2_fu_353_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln57_1_fu_346_p3),10));
    zext_ln57_3_fu_327_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_channels_ch2_q0),16));
    zext_ln57_5_fu_437_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln57_2_fu_430_p3),16));
    zext_ln57_7_fu_366_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln57_1_fu_360_p2),15));
    zext_ln57_8_fu_441_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln57_reg_688),16));
    zext_ln57_9_fu_450_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_549_p3),16));
    zext_ln57_fu_323_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_channels_ch1_q0),15));
    zext_ln58_1_fu_383_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln58_1_fu_376_p3),13));
    zext_ln58_2_fu_480_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln58_1_reg_693),16));
    zext_ln58_fu_476_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1_fu_469_p3),16));
    zext_ln59_1_fu_421_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_540_p3),16));
    zext_ln59_fu_407_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln2_fu_400_p3),14));
end behav;
