-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1.1 (64-bit)
-- Version: 2021.1.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity yuv_filter_yuv_scale is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    in_channels_ch1_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    in_channels_ch1_empty_n : IN STD_LOGIC;
    in_channels_ch1_read : OUT STD_LOGIC;
    in_channels_ch2_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    in_channels_ch2_empty_n : IN STD_LOGIC;
    in_channels_ch2_read : OUT STD_LOGIC;
    in_channels_ch3_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    in_channels_ch3_empty_n : IN STD_LOGIC;
    in_channels_ch3_read : OUT STD_LOGIC;
    in_width_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    in_width_empty_n : IN STD_LOGIC;
    in_width_read : OUT STD_LOGIC;
    in_height_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    in_height_empty_n : IN STD_LOGIC;
    in_height_read : OUT STD_LOGIC;
    out_channels_ch1_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    out_channels_ch1_full_n : IN STD_LOGIC;
    out_channels_ch1_write : OUT STD_LOGIC;
    out_channels_ch2_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    out_channels_ch2_full_n : IN STD_LOGIC;
    out_channels_ch2_write : OUT STD_LOGIC;
    out_channels_ch3_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    out_channels_ch3_full_n : IN STD_LOGIC;
    out_channels_ch3_write : OUT STD_LOGIC;
    out_width_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_width_full_n : IN STD_LOGIC;
    out_width_write : OUT STD_LOGIC;
    out_height_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_height_full_n : IN STD_LOGIC;
    out_height_write : OUT STD_LOGIC;
    Y_scale_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    Y_scale_empty_n : IN STD_LOGIC;
    Y_scale_read : OUT STD_LOGIC;
    U_scale_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    U_scale_empty_n : IN STD_LOGIC;
    U_scale_read : OUT STD_LOGIC;
    V_scale_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    V_scale_empty_n : IN STD_LOGIC;
    V_scale_read : OUT STD_LOGIC );
end;


architecture behav of yuv_filter_yuv_scale is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal in_width_blk_n : STD_LOGIC;
    signal in_height_blk_n : STD_LOGIC;
    signal out_width_blk_n : STD_LOGIC;
    signal out_height_blk_n : STD_LOGIC;
    signal Y_scale_blk_n : STD_LOGIC;
    signal U_scale_blk_n : STD_LOGIC;
    signal V_scale_blk_n : STD_LOGIC;
    signal V_scale_1_reg_128 : STD_LOGIC_VECTOR (7 downto 0);
    signal U_scale_1_reg_133 : STD_LOGIC_VECTOR (7 downto 0);
    signal Y_scale_1_reg_138 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_122_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal bound_reg_153 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_ap_start : STD_LOGIC;
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_ap_done : STD_LOGIC;
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_ap_idle : STD_LOGIC;
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_ap_ready : STD_LOGIC;
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_in_channels_ch1_read : STD_LOGIC;
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_in_channels_ch2_read : STD_LOGIC;
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_in_channels_ch3_read : STD_LOGIC;
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_out_channels_ch1_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_out_channels_ch1_write : STD_LOGIC;
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_out_channels_ch2_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_out_channels_ch2_write : STD_LOGIC;
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_out_channels_ch3_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_out_channels_ch3_write : STD_LOGIC;
    signal grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_block_state1 : BOOLEAN;
    signal grp_fu_122_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_122_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_122_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal grp_fu_122_p00 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_122_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component yuv_filter_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_channels_ch1_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        in_channels_ch1_empty_n : IN STD_LOGIC;
        in_channels_ch1_read : OUT STD_LOGIC;
        in_channels_ch2_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        in_channels_ch2_empty_n : IN STD_LOGIC;
        in_channels_ch2_read : OUT STD_LOGIC;
        in_channels_ch3_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        in_channels_ch3_empty_n : IN STD_LOGIC;
        in_channels_ch3_read : OUT STD_LOGIC;
        out_channels_ch1_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        out_channels_ch1_full_n : IN STD_LOGIC;
        out_channels_ch1_write : OUT STD_LOGIC;
        out_channels_ch2_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        out_channels_ch2_full_n : IN STD_LOGIC;
        out_channels_ch2_write : OUT STD_LOGIC;
        out_channels_ch3_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        out_channels_ch3_full_n : IN STD_LOGIC;
        out_channels_ch3_write : OUT STD_LOGIC;
        bound : IN STD_LOGIC_VECTOR (31 downto 0);
        zext_ln137 : IN STD_LOGIC_VECTOR (7 downto 0);
        zext_ln138 : IN STD_LOGIC_VECTOR (7 downto 0);
        zext_ln139 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component yuv_filter_mul_mul_16ns_16ns_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94 : component yuv_filter_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_ap_start,
        ap_done => grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_ap_done,
        ap_idle => grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_ap_idle,
        ap_ready => grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_ap_ready,
        in_channels_ch1_dout => in_channels_ch1_dout,
        in_channels_ch1_empty_n => in_channels_ch1_empty_n,
        in_channels_ch1_read => grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_in_channels_ch1_read,
        in_channels_ch2_dout => in_channels_ch2_dout,
        in_channels_ch2_empty_n => in_channels_ch2_empty_n,
        in_channels_ch2_read => grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_in_channels_ch2_read,
        in_channels_ch3_dout => in_channels_ch3_dout,
        in_channels_ch3_empty_n => in_channels_ch3_empty_n,
        in_channels_ch3_read => grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_in_channels_ch3_read,
        out_channels_ch1_din => grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_out_channels_ch1_din,
        out_channels_ch1_full_n => out_channels_ch1_full_n,
        out_channels_ch1_write => grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_out_channels_ch1_write,
        out_channels_ch2_din => grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_out_channels_ch2_din,
        out_channels_ch2_full_n => out_channels_ch2_full_n,
        out_channels_ch2_write => grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_out_channels_ch2_write,
        out_channels_ch3_din => grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_out_channels_ch3_din,
        out_channels_ch3_full_n => out_channels_ch3_full_n,
        out_channels_ch3_write => grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_out_channels_ch3_write,
        bound => bound_reg_153,
        zext_ln137 => Y_scale_1_reg_138,
        zext_ln138 => U_scale_1_reg_133,
        zext_ln139 => V_scale_1_reg_128);

    mul_mul_16ns_16ns_32_4_1_U51 : component yuv_filter_mul_mul_16ns_16ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_122_p0,
        din1 => grp_fu_122_p1,
        ce => grp_fu_122_ce,
        dout => grp_fu_122_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_ap_done = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_ap_ready = ap_const_logic_1)) then 
                    grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                U_scale_1_reg_133 <= U_scale_dout;
                V_scale_1_reg_128 <= V_scale_dout;
                Y_scale_1_reg_138 <= Y_scale_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                bound_reg_153 <= grp_fu_122_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, in_width_empty_n, in_height_empty_n, out_width_full_n, out_height_full_n, Y_scale_empty_n, U_scale_empty_n, V_scale_empty_n, grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_ap_done, ap_CS_fsm_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((out_height_full_n = ap_const_logic_0) or (out_width_full_n = ap_const_logic_0) or (in_height_empty_n = ap_const_logic_0) or (in_width_empty_n = ap_const_logic_0) or (ap_const_logic_0 = V_scale_empty_n) or (ap_const_logic_0 = U_scale_empty_n) or (ap_const_logic_0 = Y_scale_empty_n) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;

    U_scale_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, U_scale_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            U_scale_blk_n <= U_scale_empty_n;
        else 
            U_scale_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    U_scale_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, in_width_empty_n, in_height_empty_n, out_width_full_n, out_height_full_n, Y_scale_empty_n, U_scale_empty_n, V_scale_empty_n)
    begin
        if ((not(((out_height_full_n = ap_const_logic_0) or (out_width_full_n = ap_const_logic_0) or (in_height_empty_n = ap_const_logic_0) or (in_width_empty_n = ap_const_logic_0) or (ap_const_logic_0 = V_scale_empty_n) or (ap_const_logic_0 = U_scale_empty_n) or (ap_const_logic_0 = Y_scale_empty_n) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            U_scale_read <= ap_const_logic_1;
        else 
            U_scale_read <= ap_const_logic_0;
        end if; 
    end process;


    V_scale_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, V_scale_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            V_scale_blk_n <= V_scale_empty_n;
        else 
            V_scale_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    V_scale_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, in_width_empty_n, in_height_empty_n, out_width_full_n, out_height_full_n, Y_scale_empty_n, U_scale_empty_n, V_scale_empty_n)
    begin
        if ((not(((out_height_full_n = ap_const_logic_0) or (out_width_full_n = ap_const_logic_0) or (in_height_empty_n = ap_const_logic_0) or (in_width_empty_n = ap_const_logic_0) or (ap_const_logic_0 = V_scale_empty_n) or (ap_const_logic_0 = U_scale_empty_n) or (ap_const_logic_0 = Y_scale_empty_n) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            V_scale_read <= ap_const_logic_1;
        else 
            V_scale_read <= ap_const_logic_0;
        end if; 
    end process;


    Y_scale_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, Y_scale_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Y_scale_blk_n <= Y_scale_empty_n;
        else 
            Y_scale_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    Y_scale_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, in_width_empty_n, in_height_empty_n, out_width_full_n, out_height_full_n, Y_scale_empty_n, U_scale_empty_n, V_scale_empty_n)
    begin
        if ((not(((out_height_full_n = ap_const_logic_0) or (out_width_full_n = ap_const_logic_0) or (in_height_empty_n = ap_const_logic_0) or (in_width_empty_n = ap_const_logic_0) or (ap_const_logic_0 = V_scale_empty_n) or (ap_const_logic_0 = U_scale_empty_n) or (ap_const_logic_0 = Y_scale_empty_n) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Y_scale_read <= ap_const_logic_1;
        else 
            Y_scale_read <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(real_start, ap_done_reg, in_width_empty_n, in_height_empty_n, out_width_full_n, out_height_full_n, Y_scale_empty_n, U_scale_empty_n, V_scale_empty_n)
    begin
        if (((out_height_full_n = ap_const_logic_0) or (out_width_full_n = ap_const_logic_0) or (in_height_empty_n = ap_const_logic_0) or (in_width_empty_n = ap_const_logic_0) or (ap_const_logic_0 = V_scale_empty_n) or (ap_const_logic_0 = U_scale_empty_n) or (ap_const_logic_0 = Y_scale_empty_n) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_ap_done)
    begin
        if ((grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, in_width_empty_n, in_height_empty_n, out_width_full_n, out_height_full_n, Y_scale_empty_n, U_scale_empty_n, V_scale_empty_n)
    begin
                ap_block_state1 <= ((out_height_full_n = ap_const_logic_0) or (out_width_full_n = ap_const_logic_0) or (in_height_empty_n = ap_const_logic_0) or (in_width_empty_n = ap_const_logic_0) or (ap_const_logic_0 = V_scale_empty_n) or (ap_const_logic_0 = U_scale_empty_n) or (ap_const_logic_0 = Y_scale_empty_n) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_ap_done, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_ap_done = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    grp_fu_122_ce_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, in_width_empty_n, in_height_empty_n, out_width_full_n, out_height_full_n, Y_scale_empty_n, U_scale_empty_n, V_scale_empty_n, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_const_logic_1 = ap_CS_fsm_state1) and ((out_height_full_n = ap_const_logic_0) or (out_width_full_n = ap_const_logic_0) or (in_height_empty_n = ap_const_logic_0) or (in_width_empty_n = ap_const_logic_0) or (ap_const_logic_0 = V_scale_empty_n) or (ap_const_logic_0 = U_scale_empty_n) or (ap_const_logic_0 = Y_scale_empty_n) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))))) then 
            grp_fu_122_ce <= ap_const_logic_0;
        else 
            grp_fu_122_ce <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_122_p0 <= grp_fu_122_p00(16 - 1 downto 0);
    grp_fu_122_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_width_dout),32));
    grp_fu_122_p1 <= grp_fu_122_p10(16 - 1 downto 0);
    grp_fu_122_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_height_dout),32));
    grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_ap_start <= grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_ap_start_reg;

    in_channels_ch1_read_assign_proc : process(grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_in_channels_ch1_read, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            in_channels_ch1_read <= grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_in_channels_ch1_read;
        else 
            in_channels_ch1_read <= ap_const_logic_0;
        end if; 
    end process;


    in_channels_ch2_read_assign_proc : process(grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_in_channels_ch2_read, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            in_channels_ch2_read <= grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_in_channels_ch2_read;
        else 
            in_channels_ch2_read <= ap_const_logic_0;
        end if; 
    end process;


    in_channels_ch3_read_assign_proc : process(grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_in_channels_ch3_read, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            in_channels_ch3_read <= grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_in_channels_ch3_read;
        else 
            in_channels_ch3_read <= ap_const_logic_0;
        end if; 
    end process;


    in_height_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, in_height_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            in_height_blk_n <= in_height_empty_n;
        else 
            in_height_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_height_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, in_width_empty_n, in_height_empty_n, out_width_full_n, out_height_full_n, Y_scale_empty_n, U_scale_empty_n, V_scale_empty_n)
    begin
        if ((not(((out_height_full_n = ap_const_logic_0) or (out_width_full_n = ap_const_logic_0) or (in_height_empty_n = ap_const_logic_0) or (in_width_empty_n = ap_const_logic_0) or (ap_const_logic_0 = V_scale_empty_n) or (ap_const_logic_0 = U_scale_empty_n) or (ap_const_logic_0 = Y_scale_empty_n) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            in_height_read <= ap_const_logic_1;
        else 
            in_height_read <= ap_const_logic_0;
        end if; 
    end process;


    in_width_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, in_width_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            in_width_blk_n <= in_width_empty_n;
        else 
            in_width_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_width_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, in_width_empty_n, in_height_empty_n, out_width_full_n, out_height_full_n, Y_scale_empty_n, U_scale_empty_n, V_scale_empty_n)
    begin
        if ((not(((out_height_full_n = ap_const_logic_0) or (out_width_full_n = ap_const_logic_0) or (in_height_empty_n = ap_const_logic_0) or (in_width_empty_n = ap_const_logic_0) or (ap_const_logic_0 = V_scale_empty_n) or (ap_const_logic_0 = U_scale_empty_n) or (ap_const_logic_0 = Y_scale_empty_n) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            in_width_read <= ap_const_logic_1;
        else 
            in_width_read <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_ap_done, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_ap_done = ap_const_logic_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    out_channels_ch1_din <= grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_out_channels_ch1_din;

    out_channels_ch1_write_assign_proc : process(grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_out_channels_ch1_write, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            out_channels_ch1_write <= grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_out_channels_ch1_write;
        else 
            out_channels_ch1_write <= ap_const_logic_0;
        end if; 
    end process;

    out_channels_ch2_din <= grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_out_channels_ch2_din;

    out_channels_ch2_write_assign_proc : process(grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_out_channels_ch2_write, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            out_channels_ch2_write <= grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_out_channels_ch2_write;
        else 
            out_channels_ch2_write <= ap_const_logic_0;
        end if; 
    end process;

    out_channels_ch3_din <= grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_out_channels_ch3_din;

    out_channels_ch3_write_assign_proc : process(grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_out_channels_ch3_write, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            out_channels_ch3_write <= grp_yuv_scale_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y_fu_94_out_channels_ch3_write;
        else 
            out_channels_ch3_write <= ap_const_logic_0;
        end if; 
    end process;


    out_height_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, out_height_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            out_height_blk_n <= out_height_full_n;
        else 
            out_height_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_height_din <= in_height_dout;

    out_height_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, in_width_empty_n, in_height_empty_n, out_width_full_n, out_height_full_n, Y_scale_empty_n, U_scale_empty_n, V_scale_empty_n)
    begin
        if ((not(((out_height_full_n = ap_const_logic_0) or (out_width_full_n = ap_const_logic_0) or (in_height_empty_n = ap_const_logic_0) or (in_width_empty_n = ap_const_logic_0) or (ap_const_logic_0 = V_scale_empty_n) or (ap_const_logic_0 = U_scale_empty_n) or (ap_const_logic_0 = Y_scale_empty_n) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            out_height_write <= ap_const_logic_1;
        else 
            out_height_write <= ap_const_logic_0;
        end if; 
    end process;


    out_width_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, out_width_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            out_width_blk_n <= out_width_full_n;
        else 
            out_width_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_width_din <= in_width_dout;

    out_width_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, in_width_empty_n, in_height_empty_n, out_width_full_n, out_height_full_n, Y_scale_empty_n, U_scale_empty_n, V_scale_empty_n)
    begin
        if ((not(((out_height_full_n = ap_const_logic_0) or (out_width_full_n = ap_const_logic_0) or (in_height_empty_n = ap_const_logic_0) or (in_width_empty_n = ap_const_logic_0) or (ap_const_logic_0 = V_scale_empty_n) or (ap_const_logic_0 = U_scale_empty_n) or (ap_const_logic_0 = Y_scale_empty_n) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            out_width_write <= ap_const_logic_1;
        else 
            out_width_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
